version: 3

project:
  locator: SolaceLabs_solace-tryme-cli
  id: SolaceLabs_solace-tryme-cli
  name: solace-tryme-cli
  teams: []
  labels:
    - typescript

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
