export const messagePropertiesJson = [
{
    key: 'acknowledgeImmediately',
    name: 'Acknowledge Immediately',
    description: 'Flag for immediate message acknowledgment',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'payloadType',
    name: 'Payload Type',
    description: 'Hint on the payload type (BYTES or TEXT)',
    values: ['', 'BYTES', 'TEXT'],
    type: 'select',
    datatype: 'string',
    default: 'BYTES',
  }, {
    key: 'publishConfirmation',
    name: 'Publish Confirmation',
    description: 'Generate publish confirmation',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  }, {
    key: 'appMessageId',
    name: 'Application Message ID',
    description: 'User-defined identifier carried end-to-end',
    values: ['', 'uuid'],
    type: 'select',
    datatype: 'string',
    default: '',
  },{
    key: 'appMessageType',
    name: 'Application Message Type',
    description: 'User-defined message type identifier',
    type: 'input',
    datatype: 'string',
    default: '',
  },{
    key: 'correlationId',
    name: 'Correlation ID',
    description: 'User-defined identifier carried end-to-end used for peer-to-peer message synchronization (request-reply)',
    values: ['', 'uuid'],
    type: 'select',
    datatype: 'string',
    default: '',
  },{
    key: 'correlationKey',
    name: 'Correlation Key',
    description: 'Local identifier for Guaranteed messages (UUID) used to correlate a message with its acknowledgement or rejection',
    values: ['', 'uuid'],
    type: 'select',
    datatype: 'string',
    default: '',
  },{
    key: 'deliveryMode',
    name: 'Delivery Mode',
    description: 'Specifies the message delivery mode',
    values: ['', 'DIRECT', 'PERSISTENT'],
    type: 'select',
    datatype: 'string',
    default: 'PERSISTENT',
  },{
    key: 'dmqEligible',
    name: 'DMQ Eligible',
    description: 'Boolean flag for Dead Message Queue eligibility',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'elidingEligible',
    name: 'Eliding Eligible',
    description: 'Indicates if the message can be elided (replaced by newer messages)',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'replyToTopic',
    name: 'Reply To',
    description: 'Destination for replies (must be a topic)',
    type: 'input',
    datatype: 'string',
    default: '',
  },{
    key: 'sequenceNumber',
    name: 'Sequence Number',
    description: 'Message sequence identifier',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'timeToLive',
    name: 'Time to Live',
    description: 'Message expiration time in milliseconds',
    type: 'input',
    datatype: 'number',
    default: '',
  },{
    key: 'userProperties',
    name: 'User Properties',
    description: 'User properties as space-separated values if listing more than one (e.g., "key1:1st Value" key2:"2nd Value" key3:3rdValue)',
    type: 'input',
    datatype: 'string',
    default: '',
  },{
    key: 'httpContentType',
    name: 'HTTP Content Type',
    description: 'MIME type of HTTP content',
    type: 'input',
    datatype: 'string',
    default: '',
  },{
    key: 'httpContentEncoding',
    name: 'HTTP Content Encoding',
    description: 'Encoding of HTTP content',
    type: 'input',
    datatype: 'string',
    default: '',
  }

]
