export const sessionPropertiesJson = [
  {
    key: 'connectRetriesPerHost',
    name: 'Connection Retries Per Host',
    description: 'Number of retries per host',
    type: 'input',
    datatype: 'number',
    default: 3
  }, {
    key: 'connectRetries',
    name: 'Initial Connection Retries',
    description: 'Number of connection retries during initial connection setup',
    type: 'input',
    datatype: 'number',
    default: 3
  }, {
    key: 'connectTimeoutInMsecs',
    name: 'Connection Timeout (ms)',
    description: 'Connection timeout period in milliseconds',
    type: 'input',
    datatype: 'number',
    default: 3000,
  }, {
    key: 'reconnectRetries',
    name: 'Reconnect Retries',
    description: 'Number of reconnection attempts',
    type: 'input',
    datatype: 'number',
    default: 3,
  }, {
    key: 'reconnectRetryWaitInMsecs',
    name: 'Reconnect Retry Wait (ms)',
    description: 'Wait time between connection attempts',
    type: 'input',
    datatype: 'number',
    default: 3000,
  },{
    key: 'readTimeoutInMsecs',
    name: 'Read Timeout (ms)',
    description: 'Timeout period (ms) for a reply to come back from Broker',
    type: 'input',
    datatype: 'number',
    default: 10000,
  },{
    key: 'includeSenderId',
    name: 'Include Sender ID',
    description: 'Include sender ID in the message',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'clientName',
    name: 'Client Name',
    description: 'Unique identifier for the session',
    type: 'input',
    datatype: 'string',
    default: '',
  },{
    key: 'applicationDescription',
    name: 'Application Description',
    description: 'Description of the application instance',
    type: 'input',
    datatype: 'string',
    default: '',
  },{
    key: 'generateReceiveTimestamps',
    name: 'Generate Receive Timestamps',
    description: 'Enable receive timestamps',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'generateSendTimestamps',
    name: 'Generate Send Timestamps',
    description: 'Enable send timestamps',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'generateSequenceNumber',
    name: 'Generate Sequence Number',
    description: 'Enable sequence numbers',
    values: ['', 'true', 'false'],
    type: 'select',
    datatype: 'boolean',
    default: 'false',
  },{
    key: 'sendBufferMaxSize',
    name: 'Send Buffer Max Size',
    description: 'Maximum buffer size for transport session',
    type: 'input',
    datatype: 'number',
    default: 65536,
  }, {
    key: 'keepAliveIntervalInMsecs',
    name: 'Keep Alive Interval (ms)',
    description: 'Keep-alive message interval',
    type: 'input',
    datatype: 'number',
    default: 3000,
  }, {
    key: 'keepAliveIntervalsLimit',
    name: 'Keep Alive Intervals Limit',
    description: 'Maximum keep-alive messages without response',
    type: 'input',
    datatype: 'number',
    default: 3,
  }
];
