export const sessionPropertiesJson = {
	"applicationDescription": {
		"exposed": true,
		"key": "applicationDescription",
		"property": "Application Description",
		"description": "Description of the application instance",
		"type": "input",
		"datatype": "string",
		"default": "Application generated by Solace Try-Me Feed Generator."
	},
	"clientName": {
		"exposed": true,
		"key": "clientName",
		"property": "Client Name",
		"description": "Unique identifier for the session<br>(a default name is generated if not provided: stm_feed_[timestamp])",
		"type": "input",
		"datatype": "string",
		"default": ""
	},
	"compression": {
		"exposed": true,
		"key": "compression",
		"property": "Enable Compression",
		"description": "Enable payload compression",
		"values": [
			"true",
			"false"
		],
		"type": "select",
		"datatype": "boolean",
		"default": "false"
	},
	"connectRetries": {
		"exposed": false,
		"key": "connectRetries",
		"property": "Initial Connection Retries",
		"description": "Number of connection retries during initial connection setup",
		"type": "input",
		"datatype": "number",
		"default": 3
	},
	"connectTimeoutInMsecs": {
		"exposed": false,
		"key": "connectTimeoutInMsecs",
		"property": "Connection Timeout (ms)",
		"description": "Connection timeout period in milliseconds",
		"type": "input",
		"datatype": "number",
		"default": 3000
	},
  "deliveryMode": {
    "exposed": true,
    "key": "deliveryMode",
    "property": "Delivery Mode",
    "description": "Specifies the message delivery mode",
    "values": ["Direct", "Guaranteed"],
    "type": "select",
    "datatype": "string",
    "default": "Direct"
  },
	"generateSendTimestamps": {
		"exposed": true,
		"key": "generateSendTimestamps",
		"property": "Generate Send Timestamps",
		"description": "Enable send timestamps",
		"values": [
			"true",
			"false"
		],
		"type": "select",
		"datatype": "boolean",
		"default": "false"
	},
	"generateSequenceNumber": {
		"exposed": false,
		"key": "generateSequenceNumber",
		"property": "Generate Sequence Number",
		"description": "Enable sequence numbers",
		"values": [
			"true",
			"false"
		],
		"type": "select",
		"datatype": "boolean",
		"default": "false"
	},
	"includeSenderId": {
		"exposed": true,
		"key": "includeSenderId",
		"property": "Include Sender ID",
		"description": "Include sender ID in the message",
		"values": [
			"true",
			"false"
		],
		"type": "select",
		"datatype": "boolean",
		"default": "false"
	},
	"keepAliveIntervalInMsecs": {
		"exposed": false,
		"key": "keepAliveIntervalInMsecs",
		"property": "Keep Alive Interval (ms)",
		"description": "Keep-alive message interval",
		"type": "input",
		"datatype": "number",
		"default": 3000
	},
	"keepAliveIntervalsLimit": {
		"exposed": false,
		"key": "keepAliveIntervalsLimit",
		"property": "Keep Alive Intervals Limit",
		"description": "Maximum keep-alive messages without response",
		"type": "input",
		"datatype": "number",
		"default": 3
	},
	"messageFormat": {
		"exposed": true,
		"key": "messageFormat",
		"property": "Message Format",
		"description": "Hint on the message type (BYTES or TEXT)",
		"values": [
			"BYTES",
			"TEXT"
		],
		"type": "select",
		"datatype": "string",
		"default": "BYTES"
	},
	"readTimeoutInMsecs": {
		"exposed": false,
		"key": "readTimeoutInMsecs",
		"property": "Read Timeout (ms)",
		"description": "Timeout period (ms) for a reply to come back from Broker",
		"type": "input",
		"datatype": "number",
		"default": 10000
	},
	"reconnectRetries": {
		"exposed": false,
		"key": "reconnectRetries",
		"property": "Reconnect Retries",
		"description": "Number of reconnection attempts",
		"type": "input",
		"datatype": "number",
		"default": 3
	},
	"reconnectRetryWaitInMsecs": {
		"exposed": false,
		"key": "reconnectRetryWaitInMsecs",
		"property": "Reconnect Retry Wait (ms)",
		"description": "Wait time between connection attempts",
		"type": "input",
		"datatype": "number",
		"default": 3000
	},
	"sendBufferMaxSize": {
		"exposed": false,
		"key": "sendBufferMaxSize",
		"property": "Send Buffer Max Size",
		"description": "Maximum buffer size for transport session",
		"type": "input",
		"datatype": "number",
		"default": 65535
	}
};
