name: Release Artifacts
on:
  push:
    tags:
     - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build
        
      - name: Package
        run: yarn run package

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Rename stm-macos
        run: mv release/stm-macos stm

      - name: Bundle stm-macos
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/stm-macos-${{ steps.package-version.outputs.current-version}}.zip stm

      - name: Remove stm (of macos)
        run: rm stm
      
      - name: Rename stm-linux
        run: mv release/stm-linux stm

      - name: Bundle stm-linux
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/stm-linux-${{ steps.package-version.outputs.current-version}}.zip stm

      - name: Remove stm (of linux)
        run: rm stm

      - name: Rename stm-alpine
        run: mv release/stm-alpine stm

      - name: Bundle stm-alpine
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/stm-alpine-${{ steps.package-version.outputs.current-version}}.zip stm

      - name: Remove stm (of alpine)
        run: rm stm

      - name: Rename stm-win
        run: mv release/stm-win.exe stm.exe

      - name: Bundle stm-win
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/stm-win-${{ steps.package-version.outputs.current-version}}.zip stm.exe

      - name: Remove stm (of win)
        run: rm stm.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
