name: Release Artifacts
on:
  push:
    tags:
     - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build
        
      - name: Package
        run: yarn run package

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      - name: Install zip command line tool
        run: sudo apt-get install zip

      - name: Prepare stm archives for different targets
        run: |
          zip -qq -r release/stm-macos-v${{ steps.package-version.outputs.current-version}}.zip stm-macos
          zip -qq -r release/stm-linux-v${{ steps.package-version.outputs.current-version}}.zip stm-linux
          zip -qq -r release/stm-alpine-v${{ steps.package-version.outputs.current-version}}.zip stm-alpine
          zip -qq -r release/stm-win-v${{ steps.package-version.outputs.current-version}}.zip stm.exe
          rm releases/stm-macos releases/stm-linux releases/stm-alpine releases/stm.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
