name: Release
on:
  push:
    tags:
     - 'v*.*.*'  # Matches version tags like v1.0.0

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build
        
      - name: Package
        run: yarn run package

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Prepare stm archives for different targets
        run: |
          cd release
          zip -qq -r stm-macos-v${{ steps.package-version.outputs.current-version}}.zip . -i stm-macos
          zip -qq -r stm-linux-v${{ steps.package-version.outputs.current-version}}.zip . -i stm-linux
          zip -qq -r stm-alpine-v${{ steps.package-version.outputs.current-version}}.zip . -i stm-alpine
          zip -qq -r stm-win-v${{ steps.package-version.outputs.current-version}}.zip . -i stm-win.exe
          cd ..
      
      - name: Publish artifacts to github
        uses: softprops/action-gh-release@v1
        with:
          files: release/*

      - name: Update Homebrew 
        run: ./scripts/update_homebrew.sh ${{ steps.package-version.outputs.current-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.SOLLYBOT_GITHUB_PAT }}

      - name: Generate .deb package
        run: |
          mkdir -p stm-linux_${{ steps.package-version.outputs.current-version}}_amd64
          cd stm-linux_${{ steps.package-version.outputs.current-version}}_amd64
          mkdir -p usr/bin
          cp ../release/stm-linux usr/bin/stm
          mkdir -p DEBIAN
          echo "Package: stm
          Version: ${{ steps.package-version.outputs.current-version}}
          Maintainer: SolaceCommunity <community@solace.dev>
          Depends: libc6
          Section: utils
          Architecture: amd64
          Homepage: http://solace.dev
          Description: This is a command line tool to help you get started with Solace PubSub+ Event Broker" \
          > DEBIAN/control
          cd ../
          dpkg --build ./stm-linux_${{ steps.package-version.outputs.current-version}}_amd64
          dpkg --info stm-linux_${{ steps.package-version.outputs.current-version}}_amd64.deb

      - name: Update APT Repository
        run: ./scripts/update_apt.sh ${{ steps.package-version.outputs.current-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.SOLLYBOT_GITHUB_PAT }}

      # - name: Update Chocolatey
      #   run: ./scripts/update_chocolatey.sh


